# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liu.Colors'),
        ),
        migrations.AddField(
            model_name='child',
            name='favor',
            field=models.ManyToManyField(to='liu.Colors'),
        ),
        migrations.AddField(
            model_name='ball',
            name='color',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liu.Colors'),
        ),
    ]
